import { UserProfile, Meeting, Trip, ChurchEvent, Announcement, RewardItem, AttendanceRecord, FollowUpRecord, SystemSettings } from '../types';

export const INITIAL_SETTINGS: SystemSettings = {
  followUpThresholds: {
    yellowAbsences: 2,
    orangeAbsences: 3,
    redAbsences: 4,
  },
  pointRules: {
    meetingAttendance: 10,
    spiritualDay: 20,
    conference: 30,
    activity: 20,
  },
  ageGroups: [
    { id: 'middle_school', nameAr: 'إعدادي' },
    { id: 'secondary', nameAr: 'ثانوي' },
    { id: 'university', nameAr: 'جامعي' },
    { id: 'graduate', nameAr: 'خريجين' },
  ],
};

export const INITIAL_USERS: UserProfile[] = [
  {
    userId: 'user_mina_01',
    userCode: 'YT_000101',
    displayName: 'مينا عادل فوزي',
    nickname: 'مينا',
    phoneNumber: '01223456781',
    whatsappNumber: '01223456781',
    role: 'youth',
    gender: 'male',
    birthDate: '2004-05-14',
    educationStage: 'university',
    faculty: 'هندسة حاسبات',
    academicYear: 'الفرقة الثالثة',
    scheduleType: 'regular',
    weeklySchedule: {
      sat: 'study',
      sun: 'study',
      mon: 'study',
      tue: 'study',
      wed: 'available',
      thu: 'available',
      fri: 'available',
    },
    assignedServantId: 'servant_maged_01',
    assignedServantName: 'خ. ماجد فوزي',
    totalAttendances: 27,
    currentStreak: 4,
    bestStreak: 9,
    totalPoints: 380,
    lastAttendedAt: '2026-09-06',
    consecutiveAbsences: 0,
    followUpStatus: 'regular',
    password: 'Youth@2026',
    createdAt: '2025-01-10',
    updatedAt: '2026-09-06',
  },
  {
    userId: 'user_bishoy_02',
    userCode: 'YT_000102',
    displayName: 'بيشوي سامي عزيز',
    nickname: 'بيشو',
    phoneNumber: '01012345672',
    whatsappNumber: '01012345672',
    role: 'youth',
    gender: 'male',
    birthDate: '2003-11-20',
    educationStage: 'university',
    faculty: 'تجارة إنجليزي',
    academicYear: 'الفرقة الرابعة',
    scheduleType: 'variable',
    weeklySchedule: {
      sat: 'work',
      sun: 'work',
      mon: 'work',
      tue: 'work',
      wed: 'work',
      thu: 'study',
      fri: 'available',
    },
    assignedServantId: 'servant_maged_01',
    assignedServantName: 'خ. ماجد فوزي',
    totalAttendances: 14,
    currentStreak: 0,
    bestStreak: 6,
    totalPoints: 190,
    lastAttendedAt: '2026-08-23',
    consecutiveAbsences: 3,
    followUpStatus: 'needs_followup',
    password: 'Youth@2026',
    createdAt: '2025-02-15',
    updatedAt: '2026-09-06',
  },
  {
    userId: 'user_maryam_03',
    userCode: 'YT_000103',
    displayName: 'مريم نبيل كامل',
    nickname: 'ماري',
    phoneNumber: '01123456783',
    whatsappNumber: '01123456783',
    role: 'youth',
    gender: 'female',
    birthDate: '2005-08-12',
    educationStage: 'university',
    faculty: 'صيدلة',
    academicYear: 'الفرقة الثانية',
    scheduleType: 'regular',
    weeklySchedule: {
      sat: 'study',
      sun: 'study',
      mon: 'study',
      tue: 'study',
      wed: 'study',
      thu: 'available',
      fri: 'available',
    },
    assignedServantId: 'servant_dina_02',
    assignedServantName: 'ت. دينا سمير',
    totalAttendances: 31,
    currentStreak: 8,
    bestStreak: 12,
    totalPoints: 460,
    lastAttendedAt: '2026-09-06',
    consecutiveAbsences: 0,
    followUpStatus: 'regular',
    password: 'Youth@2026',
    createdAt: '2025-01-05',
    updatedAt: '2026-09-06',
  },
  {
    userId: 'user_kirollos_04',
    userCode: 'YT_000104',
    displayName: 'كيرلس مجدي نجيب',
    nickname: 'كيرو',
    phoneNumber: '01234567894',
    whatsappNumber: '01234567894',
    role: 'youth',
    gender: 'male',
    birthDate: '2001-03-25',
    educationStage: 'graduate',
    jobTitle: 'مهندس برمجيات',
    workplace: 'القرية الذكية',
    scheduleType: 'regular',
    weeklySchedule: {
      sat: 'available',
      sun: 'work',
      mon: 'work',
      tue: 'work',
      wed: 'work',
      thu: 'work',
      fri: 'available',
    },
    assignedServantId: 'servant_maged_01',
    assignedServantName: 'خ. ماجد فوزي',
    totalAttendances: 9,
    currentStreak: 0,
    bestStreak: 5,
    totalPoints: 110,
    lastAttendedAt: '2026-08-09',
    consecutiveAbsences: 5,
    followUpStatus: 'urgent',
    password: 'Youth@2026',
    createdAt: '2024-11-20',
    updatedAt: '2026-09-06',
  },
  {
    userId: 'user_sara_05',
    userCode: 'YT_000105',
    displayName: 'سارة يوسف زكي',
    nickname: 'سارة',
    phoneNumber: '01098765435',
    whatsappNumber: '01098765435',
    role: 'youth',
    gender: 'female',
    birthDate: '2006-09-18',
    educationStage: 'secondary',
    faculty: 'ثانوية عامة (علمي علوم)',
    academicYear: 'الصف الثالث الثانوي',
    scheduleType: 'regular',
    weeklySchedule: {
      sat: 'study',
      sun: 'study',
      mon: 'study',
      tue: 'study',
      wed: 'study',
      thu: 'study',
      fri: 'available',
    },
    assignedServantId: 'servant_dina_02',
    assignedServantName: 'ت. دينا سمير',
    totalAttendances: 18,
    currentStreak: 0,
    bestStreak: 7,
    totalPoints: 230,
    lastAttendedAt: '2026-08-30',
    consecutiveAbsences: 2,
    followUpStatus: 'irregular',
    password: 'Youth@2026',
    createdAt: '2025-01-15',
    updatedAt: '2026-09-06',
  },
  {
    userId: 'servant_maged_01',
    userCode: 'SR_000001',
    displayName: 'خادم ماجد فوزي',
    nickname: 'ماجد',
    phoneNumber: '01221112223',
    whatsappNumber: '01221112223',
    role: 'servant',
    gender: 'male',
    educationStage: 'graduate',
    jobTitle: 'مدير مشروعات',
    scheduleType: 'regular',
    weeklySchedule: {
      sat: 'available',
      sun: 'work',
      mon: 'work',
      tue: 'work',
      wed: 'work',
      thu: 'available',
      fri: 'available',
    },
    totalAttendances: 45,
    currentStreak: 15,
    bestStreak: 25,
    totalPoints: 950,
    consecutiveAbsences: 0,
    followUpStatus: 'regular',
    password: 'Servant@2026',
    createdAt: '2024-01-01',
    updatedAt: '2026-09-06',
  },
  {
    userId: 'servant_dina_02',
    userCode: 'SR_000002',
    displayName: 'تاسوني دينا سمير',
    nickname: 'دينا',
    phoneNumber: '01112223334',
    whatsappNumber: '01112223334',
    role: 'servant',
    gender: 'female',
    educationStage: 'graduate',
    jobTitle: 'صيدلانية',
    scheduleType: 'regular',
    weeklySchedule: {
      sat: 'available',
      sun: 'work',
      mon: 'work',
      tue: 'work',
      wed: 'work',
      thu: 'available',
      fri: 'available',
    },
    totalAttendances: 48,
    currentStreak: 20,
    bestStreak: 30,
    totalPoints: 1100,
    consecutiveAbsences: 0,
    followUpStatus: 'regular',
    password: 'Servant@2026',
    createdAt: '2024-01-01',
    updatedAt: '2026-09-06',
  },
  {
    userId: 'canteen_servant_01',
    userCode: 'CN_000001',
    displayName: 'ميخائيل رشدي — مسؤول الكانتين',
    nickname: 'مسؤول الكانتين',
    phoneNumber: '01239998881',
    whatsappNumber: '01239998881',
    role: 'canteen_servant',
    gender: 'male',
    educationStage: 'graduate',
    jobTitle: 'مسؤول كانتين الكنيسة',
    scheduleType: 'regular',
    weeklySchedule: {
      sat: 'available',
      sun: 'available',
      mon: 'available',
      tue: 'available',
      wed: 'available',
      thu: 'available',
      fri: 'available',
    },
    totalAttendances: 50,
    currentStreak: 25,
    bestStreak: 25,
    totalPoints: 100,
    consecutiveAbsences: 0,
    followUpStatus: 'regular',
    password: 'Canteen@2026',
    createdAt: '2024-01-01',
    updatedAt: '2026-09-06',
  },
  {
    userId: 'admin_abouna_01',
    userCode: 'AD_000001',
    displayName: 'أبونا مكسيموس يوسف',
    nickname: 'أبونا',
    phoneNumber: '01000000001',
    whatsappNumber: '01000000001',
    role: 'admin',
    gender: 'male',
    educationStage: 'graduate',
    scheduleType: 'regular',
    weeklySchedule: {
      sat: 'available',
      sun: 'available',
      mon: 'available',
      tue: 'available',
      wed: 'available',
      thu: 'available',
      fri: 'available',
    },
    totalAttendances: 60,
    currentStreak: 40,
    bestStreak: 40,
    totalPoints: 2000,
    consecutiveAbsences: 0,
    followUpStatus: 'regular',
    password: 'Admin@2026',
    createdAt: '2023-09-01',
    updatedAt: '2026-09-06',
  }
];

export const INITIAL_MEETINGS: Meeting[] = [
  {
    meetingId: 'meet_2026_09_17',
    title: 'اجتماع الشباب الأسبوعي: كيف نعيش الفرح الحقيقي؟',
    description: 'لقاء مفتوح حول مواجهة ضغوط الحياة وبناء رجاء حقيقي في المسيح، يليها فقرة ترانيم وتسبيح.',
    speaker: 'أبونا مكسيموس يوسف',
    date: '2026-09-17',
    startTime: '19:30',
    endTime: '21:30',
    location: 'قاعة القديس مارجرجس الكبرى - الدور الثاني',
    status: 'active',
    qrSecretToken: 'SECRET_MEET_TOKEN_20260917',
    qrValidFrom: '2026-09-17T19:15:00Z',
    qrValidUntil: '2026-09-17T20:30:00Z',
    attendanceCount: 42,
    pointsAwarded: 10,
    createdBy: 'admin_abouna_01',
    createdAt: '2026-09-10',
  },
  {
    meetingId: 'meet_2026_09_24',
    title: 'اجتماع الشباب: إدارة الوقت والأولويات في الجامعة والعمل',
    description: 'ورشة عمل تفاعلية تليها فقرة مناقشات في مجموعات صغيرة.',
    speaker: 'م. مينا فوزي',
    date: '2026-09-24',
    startTime: '19:30',
    endTime: '21:30',
    location: 'قاعة القديس مارجرجس الكبرى',
    status: 'scheduled',
    qrSecretToken: 'SECRET_MEET_TOKEN_20260924',
    qrValidFrom: '2026-09-24T19:15:00Z',
    qrValidUntil: '2026-09-24T20:30:00Z',
    attendanceCount: 0,
    pointsAwarded: 10,
    createdBy: 'admin_abouna_01',
    createdAt: '2026-09-10',
  },
  {
    meetingId: 'meet_2026_09_10',
    title: 'اجتماع الشباب: بداية سنة خدمة جديدة وميثاق المحبة',
    description: 'كلمة افتتاحية ولقاء روحي وبانوراما أنشطة الصيف والخريف.',
    speaker: 'أبونا مكسيموس يوسف',
    date: '2026-09-10',
    startTime: '19:30',
    endTime: '21:30',
    location: 'قاعة القديس مارجرجس الكبرى',
    status: 'completed',
    qrSecretToken: 'SECRET_MEET_TOKEN_20260910',
    qrValidFrom: '2026-09-10T19:15:00Z',
    qrValidUntil: '2026-09-10T20:30:00Z',
    attendanceCount: 97,
    pointsAwarded: 10,
    createdBy: 'admin_abouna_01',
    createdAt: '2026-09-01',
  },
  {
    meetingId: 'meet_2026_09_03',
    title: 'اجتماع الشباب الأسبوعي (مُعلّق بسبب عشية عيد النيروز)',
    description: 'تم تعليق الاجتماع هذا الأسبوع لمشاركة شباب الكنيسة في عشية وتسبحة عيد النيروز رأس السنة القبطية.',
    speaker: 'أمانة الخدمة',
    date: '2026-09-03',
    startTime: '19:30',
    endTime: '21:30',
    location: 'الكنيسة الكبرى',
    status: 'canceled',
    qrSecretToken: 'SECRET_MEET_TOKEN_20260903',
    qrValidFrom: '2026-09-03T19:15:00Z',
    qrValidUntil: '2026-09-03T20:30:00Z',
    attendanceCount: 0,
    pointsAwarded: 0,
    createdBy: 'admin_abouna_01',
    createdAt: '2026-08-25',
  },
  {
    meetingId: 'meet_2026_08_27',
    title: 'اجتماع الشباب: النضج الوجداني والعلاقات المسيحية النقية',
    description: 'محاضرة وورشة حوارية حول تدبير المشاعر والنضج الشخصي في مرحلة الشباب.',
    speaker: 'د. عادل توفيق',
    date: '2026-08-27',
    startTime: '19:30',
    endTime: '21:30',
    location: 'قاعة القديس مارجرجس الكبرى',
    status: 'completed',
    qrSecretToken: 'SECRET_MEET_TOKEN_20260827',
    qrValidFrom: '2026-08-27T19:15:00Z',
    qrValidUntil: '2026-08-27T20:30:00Z',
    attendanceCount: 91,
    pointsAwarded: 10,
    createdBy: 'admin_abouna_01',
    createdAt: '2026-08-18',
  },
  {
    meetingId: 'meet_2026_08_20',
    title: 'اجتماع الشباب: كيف تكتشف وتنمي وزناتك في الكنيسة والمجتمع؟',
    description: 'تأمل في مثل الوزنات مع تطبيقات عملية في الخدمة والحياة اليومية.',
    speaker: 'القس مرقس ميخائيل',
    date: '2026-08-20',
    startTime: '19:30',
    endTime: '21:30',
    location: 'قاعة القديس مارجرجس الكبرى',
    status: 'completed',
    qrSecretToken: 'SECRET_MEET_TOKEN_20260820',
    qrValidFrom: '2026-08-20T19:15:00Z',
    qrValidUntil: '2026-08-20T20:30:00Z',
    attendanceCount: 89,
    pointsAwarded: 10,
    createdBy: 'admin_abouna_01',
    createdAt: '2026-08-10',
  },
  {
    meetingId: 'meet_2026_08_13',
    title: 'اجتماع الشباب: الصلاة في المخدع والانتصار على التشتت',
    description: 'تدريب روحي عملي على قراءة المزامير والتأمل الفردي.',
    speaker: 'أبونا مكسيموس يوسف',
    date: '2026-08-13',
    startTime: '19:30',
    endTime: '21:30',
    location: 'قاعة القديس مارجرجس الكبرى',
    status: 'completed',
    qrSecretToken: 'SECRET_MEET_TOKEN_20260813',
    qrValidFrom: '2026-08-13T19:15:00Z',
    qrValidUntil: '2026-08-13T20:30:00Z',
    attendanceCount: 86,
    pointsAwarded: 10,
    createdBy: 'admin_abouna_01',
    createdAt: '2026-08-01',
  }
];

export const INITIAL_TRIPS: Trip[] = [
  {
    tripId: 'trip_anba_antony_2026',
    title: 'رحلة دير الأنبا أنطونيوس والأنبا بولا بالبحر الأحمر',
    description: 'يوم روحي مع زيارة المغارة القديمة وصلاة القداس الإلهي، وتأمل في حياة أبي الرهبان. يشمل الانتقالات بأتوبيسات سياحية مكيفة والوجبات.',
    imageUrl: 'https://images.unsplash.com/photo-1548625361-195fe51a37c5?auto=format&fit=crop&w=800&q=80',
    date: '2026-09-25',
    time: '06:00 ص',
    meetingPoint: 'أمام فناء الكنيسة الرئيسي',
    destinations: ['دير القديس الأنبا أنطونيوس', 'مغارة الأنبا أنطونيوس', 'دير القديس الأنبا بولا أول السواح'],
    price: 250,
    capacity: 50,
    bookedSeatsCount: 37,
    bookingDeadline: '2026-09-22',
    coordinatorName: 'الخادم مينا منير',
    coordinatorWhatsapp: '201223456789',
    status: 'open',
    createdAt: '2026-09-01',
  },
  {
    tripId: 'trip_wadi_rayan_2026',
    title: 'يوم ترفيهي وتخييم بوادي الريان والبحيرة المسحورة',
    description: 'أنشطة شبابية، تزلج على الرمال، قوارب فلوكة، وفقرة سمر روحي حول نار المساء.',
    imageUrl: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=800&q=80',
    date: '2026-10-09',
    time: '07:00 ص',
    meetingPoint: 'ساحة الكنيسة',
    destinations: ['شلالات وادي الريان', 'جبل المدورة', 'البحيرة المسحورة'],
    price: 320,
    capacity: 45,
    bookedSeatsCount: 42,
    bookingDeadline: '2026-10-05',
    coordinatorName: 'الخادم بيتر عادل',
    coordinatorWhatsapp: '201011122233',
    status: 'open',
    createdAt: '2026-09-05',
  }
];

export const INITIAL_EVENTS: ChurchEvent[] = [
  {
    eventId: 'evt_spiritual_day_2026',
    title: 'اليوم الروحي: «اثبتوا في محبتي»',
    type: 'spiritual_day',
    description: 'قداس إلهي، تسبحة، خلوة صامتة مع الإنجيل، وثلاث كلمات روحية بحضور آباء كهنة وخدام.',
    imageUrl: 'https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&w=800&q=80',
    date: '2026-10-02',
    time: '08:00 ص - 04:00 م',
    location: 'بيت الشمامسة والخلوة - أبيس',
    price: 50,
    capacity: 100,
    registrationRequired: true,
    registrationDeadline: '2026-09-30',
    status: 'upcoming',
    createdAt: '2026-09-08',
  },
  {
    eventId: 'evt_sports_tournament_2026',
    title: 'دوري كرة القدم والشطرنج لشباب الكنيسة',
    type: 'sports',
    description: 'دورة تنافسية سنوية للفرق مع جوائز وكؤوس للمراكز الثلاثة الأولى.',
    imageUrl: 'https://images.unsplash.com/photo-1529900245534-47fbfb57835a?auto=format&fit=crop&w=800&q=80',
    date: '2026-10-16',
    time: '04:00 م - 09:00 م',
    location: 'ملاعب النادي الرياضي المجاور',
    price: 0,
    capacity: 80,
    registrationRequired: true,
    registrationDeadline: '2026-10-12',
    status: 'upcoming',
    createdAt: '2026-09-08',
  }
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    announcementId: 'anc_01',
    title: 'بدء الحجز في رحلة دير الأنبا أنطونيوس',
    body: 'المقاعد محدودة (متبقي 13 مقعد فقط)، برجاء تأكيد الاشتراك مع الخادم المسؤول ودفع قيمة الاشتراك.',
    priority: 'important',
    publishedAt: '2026-09-11',
    expiresAt: '2026-09-24',
    status: 'active',
    createdBy: 'admin_abouna_01',
  },
  {
    announcementId: 'anc_02',
    title: 'تنويه: بدء تسجيل الحضور بالباركود (QR Code)',
    body: 'نرجو من جميع الشباب تجهيز هواتفهم لمسح كود الحضور الذكي في قاعة الاجتماع فور وصولهم لكسب النقاط.',
    priority: 'urgent',
    publishedAt: '2026-09-12',
    expiresAt: '2026-09-30',
    status: 'active',
    createdBy: 'admin_abouna_01',
  }
];

export const INITIAL_REWARDS: RewardItem[] = [
  {
    rewardId: 'rew_drink_100',
    title: 'مشروب مجاني من الكانتين',
    description: 'كوبون صالح لأي مشروب ساخن أو بارد في كانتين الكنيسة.',
    requiredPoints: 100,
    availableQuantity: 50,
    active: true,
  },
  {
    rewardId: 'rew_snack_250',
    title: 'سناك وباتي فريش من الكانتين',
    description: 'وجبة سريعة خفيفة مع عصير.',
    requiredPoints: 250,
    availableQuantity: 30,
    active: true,
  },
  {
    rewardId: 'rew_book_500',
    title: 'كتاب روحي قيم من مكتبة الكنيسة',
    description: 'اختر كتاباً من ترشيحات الآباء الروحية من مكتبة البيع.',
    requiredPoints: 500,
    availableQuantity: 15,
    active: true,
  },
  {
    rewardId: 'rew_hoodie_1000',
    title: 'هودي مطبوع بشعار اجتماع الشباب',
    description: 'هودي قطني عالي الجودة خاص باجتماع الشباب.',
    requiredPoints: 1000,
    availableQuantity: 8,
    active: true,
  }
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    attendanceId: 'meet_2026_09_10_user_mina_01',
    meetingId: 'meet_2026_09_10',
    meetingTitle: 'اجتماع الشباب الأسبوعي',
    meetingDate: '2026-09-10',
    userId: 'user_mina_01',
    userCode: 'YT_000101',
    userName: 'مينا عادل فوزي',
    timestamp: '2026-09-10T19:35:12Z',
    method: 'qr_scan',
    pointsAwarded: 10,
  },
  {
    attendanceId: 'meet_2026_08_27_user_mina_01',
    meetingId: 'meet_2026_08_27',
    meetingTitle: 'اجتماع الشباب الأسبوعي',
    meetingDate: '2026-08-27',
    userId: 'user_mina_01',
    userCode: 'YT_000101',
    userName: 'مينا عادل فوزي',
    timestamp: '2026-08-27T19:40:00Z',
    method: 'qr_scan',
    pointsAwarded: 10,
  },
  {
    attendanceId: 'meet_2026_08_20_user_mina_01',
    meetingId: 'meet_2026_08_20',
    meetingTitle: 'اجتماع الشباب الأسبوعي',
    meetingDate: '2026-08-20',
    userId: 'user_mina_01',
    userCode: 'YT_000101',
    userName: 'مينا عادل فوزي',
    timestamp: '2026-08-20T19:32:15Z',
    method: 'qr_scan',
    pointsAwarded: 10,
  },
  {
    attendanceId: 'meet_2026_08_13_user_mina_01',
    meetingId: 'meet_2026_08_13',
    meetingTitle: 'اجتماع الشباب الأسبوعي',
    meetingDate: '2026-08-13',
    userId: 'user_mina_01',
    userCode: 'YT_000101',
    userName: 'مينا عادل فوزي',
    timestamp: '2026-08-13T19:30:00Z',
    method: 'qr_scan',
    pointsAwarded: 10,
  },
  {
    attendanceId: 'meet_2026_09_10_user_maryam_03',
    meetingId: 'meet_2026_09_10',
    meetingTitle: 'اجتماع الشباب الأسبوعي',
    meetingDate: '2026-09-10',
    userId: 'user_maryam_03',
    userCode: 'YT_000103',
    userName: 'مريم نبيل كامل',
    timestamp: '2026-09-10T19:28:44Z',
    method: 'qr_scan',
    pointsAwarded: 10,
  }
];

export const INITIAL_FOLLOWUPS: FollowUpRecord[] = [
  {
    followupId: 'fup_001',
    recordId: 'fup_001',
    userId: 'user_bishoy_02',
    userName: 'بيشوي سامي عزيز',
    youthId: 'user_bishoy_02',
    youthName: 'بيشوي سامي عزيز',
    youthCode: 'YT_000102',
    servantId: 'servant_maged_01',
    servantName: 'خ. ماجد فوزي',
    date: '2026-09-08',
    contactMethod: 'whatsapp',
    type: 'whatsapp',
    status: 'study',
    outcome: 'مشغول بالامتحانات والمذاكرة',
    generalNotes: 'لديه امتحانات نصف الفصل الدراسي حتى الأسبوع القادم، واطمأننت عليه.',
    notes: 'لديه امتحانات نصف الفصل الدراسي حتى الأسبوع القادم، واطمأننت عليه.',
    nextFollowupDate: '2026-09-15',
    createdAt: '2026-09-08T18:00:00Z',
  },
  {
    followupId: 'fup_002',
    recordId: 'fup_002',
    userId: 'user_kirollos_04',
    userName: 'كيرلس مجدي نجيب',
    youthId: 'user_kirollos_04',
    youthName: 'كيرلس مجدي نجيب',
    youthCode: 'YT_000104',
    servantId: 'servant_maged_01',
    servantName: 'خ. ماجد فوزي',
    date: '2026-09-05',
    contactMethod: 'phone',
    type: 'phone_call',
    status: 'work',
    outcome: 'ظروف عمل ودوام متأخر',
    generalNotes: 'انتقل لمشروع جديد في القرية الذكية بمواعيد مسائية، تم التنسيق معه للتواصل تليفونياً.',
    notes: 'انتقل لمشروع جديد في القرية الذكية بمواعيد مسائية، تم التنسيق معه للتواصل تليفونياً.',
    nextFollowupDate: '2026-09-18',
    createdAt: '2026-09-05T20:30:00Z',
  }
];
